# Laboratiorio 2
## 1) Matrici e norme
Si consideri la matrice $A = \begin{pmatrix} 1 & 2 \\ 0.499 & 1.001 \end{pmatrix}$
• Calcolare la norma 1, la norma 2, la norma Frobenius e la norma infinito di A con `numpy.linalg.norm()` (guardare l’help della funzione).
• Calcolare il numero di condizionamento di A con `numpy.linalg.cond()` (guardare l’help della funzione).
• Considerare il vettore colonna $x = (1, 1)^T$ e calcolare il corrispondente termine noto $b$ per il sistema lineare $Ax = b$.
• Considerare ora il vettore $\tilde{b} = (3, 1.4985)^T$ e verifica che $\tilde{x} = (2, 0.5)^T$ è soluzione del sistema $A\tilde{x} = \tilde{b}$.
• Calcolare la norma 2 della perturbazione sui termini noti $∆b = \|b− \tilde{b}\|_2$ e la norma 2 della perturbazione sulle soluzioni $\Delta_x = \|x − \tilde{x}\|_2$. Confrontare $\Delta_b$ con $\Delta_x$.

In [35]:
import numpy as np

#help(np.linalg) # View source
#help (np.linalg.norm)
#help (np.linalg.cond)

n = 2
A = np.array([[1, 2], [0.499, 1.001]])

norm1 = np.linalg.norm(A, 1)
norm2 =  np.linalg.norm(A, 2)
normfro = np.linalg.norm(A, 'fro')
norminf = np.linalg.norm(A, np.inf)

print ('Norme di A:')
print('Norma1 =', norm1)
print('Norma2 =', norm2)
print('Normafro =', normfro)
print('Norma infinito =', norminf)

Norme di A:
Norma1 = 3.001
Norma2 = 2.500200104037774
Normafro = 2.5002003919686118
Norma infinito = 3.0


In [27]:
cond1 = np.linalg.cond(A, 1)
cond2 = np.linalg.cond(A, 2)
condfro = np.linalg.cond(A, 'fro')
condinf = np.linalg.cond(A, np.inf)

print('Numero di condizionamento di A:')
print ('K(A)_1 =', cond1)
print ('K(A)_2 =', cond2)
print ('K(A)_fro =', condfro)
print ('K(A)_inf =', condinf)

Numero di condizionamento di A:
K(A)_1 = 3001.0000000001082
K(A)_2 = 2083.666853410337
K(A)_fro = 2083.6673333334084
K(A)_inf = 3001.0000000001082


In [28]:
x = np.ones((2,1))
b = A.dot(x)

btilde = np.array([[3], [1.4985]])
xtilde = np.array([[2, 0.5]]).T

# Verificare che xtilde è soluzione di A xtilde = btilde (Axtilde)
my_btilde = A.dot(xtilde)

print ('A*xtilde =', btilde.tolist())
print(np.linalg.norm(btilde-my_btilde,'fro'))

A*xtilde = [[3.0], [1.4985]]
0.0


In [29]:
deltax = xtilde - x
deltab = btilde - b

print ('delta x =', deltax.tolist())
print ('delta b =', deltab.tolist())

delta x = [[1.0], [-0.5]]
delta b = [[0.0], [-0.0015000000000000568]]


## 2) Metodi diretti
### 2.1) Fattorizzazione LU
Si consideri la matrice $A = \begin{pmatrix} 3 & -1 & 1 & -2 \\ 0 & 2 & 5 & -1 \\ 1 & 0 & -7 & 1 \\ 0 & 2 & 1 & 1 \end{pmatrix}$
• Creare il problema test in cui il vettore della soluzione esatta è $x = (1, 1, 1, 1)^T$ e il vettore termine noto è $b = Ax$.
• Guardare l’help della funzione `scipy.linalg.lu_factor` e `scipy.linalg.lu`. Usare una delle sue funzioni per calcolare la fattorizzazione LU di A con pivoting. Verificare la correttezza dell’output.
• Risolvere il sistema lineare con la funzione `scipy.linalg.lu_solve` oppure utilizzando la funzione `scipy.linalg.solve_triangular`.
• Stampare la soluzione calcolata e valutarne la correttezza.
**NB** L’inversa di una matrice viene calcolata con la funzione `scipy.linalg.inv`.

In [30]:
# crazione dati e problema test
A = np.array ([ [3,-1, 1,-2], [0, 2, 5, -1], [1, 0, -7, 1], [0, 2, 1, 1]  ])
x = np.ones((4,1))
b = A.dot(x)

condA = np.linalg.cond(A, 'fro')

print('x:', x.tolist())
print('x.shape:', x.shape)
print('b:', b.tolist())
print('b.shape: ', b.shape)
print('A: \n', A)
print('A.shape:', A.shape)
print('K(A):', condA)

x: [[1.0], [1.0], [1.0], [1.0]]
x.shape: (4, 1)
b: [[1.0], [6.0], [-5.0], [4.0]]
b.shape:  (4, 1)
A: 
 [[ 3 -1  1 -2]
 [ 0  2  5 -1]
 [ 1  0 -7  1]
 [ 0  2  1  1]]
A.shape: (4, 4)
K(A): 16.801308003167016


In [31]:
import scipy
# help (scipy)
import scipy.linalg
# help (scipy.linalg)
from scipy.linalg import lu_factor as LUdec # pivoting
from scipy.linalg import lu as LUfull # partial pivoting

lu, piv = LUdec(A)

print('lu: \n',lu,'\n')
print('piv:',piv,'\n')

lu: 
 [[ 3.         -1.          1.         -2.        ]
 [ 0.          2.          5.         -1.        ]
 [ 0.33333333  0.16666667 -8.16666667  1.83333333]
 [ 0.          1.          0.48979592  1.10204082]] 

piv: [0 1 2 3] 


In [32]:
# risoluzione di    Ax = b   <--->  PLUx = b 
my_x = scipy.linalg.lu_solve((lu, piv), b)

print('my_x:', my_x.tolist())
print('norm:', scipy.linalg.norm(x-my_x, 'fro'))

my_x: [[1.0000000000000002], [0.9999999999999996], [1.0000000000000002], [1.0000000000000004]]
norm: 7.021666937153402e-16


In [ ]:
# IMPLEMENTAZIONE ALTERNATIVA - 1

P, L, U = ...
print ('A = ', A)
print ('P = ', P)
print ('L = ', L)
print ('U = ', U)
print ('P*L*U = ', np.matmul(P , np.matmul(L, U))) 

print ('diff = ',   np.linalg.norm(A - np.matmul(P , np.matmul(L, U)), 'fro'  ) ) 


# if P != np.eye(n): 
# Ax = b   <--->  PLUx = b  <--->  LUx = inv(P)b  <--->  Ly=inv(P)b & Ux=y : matrici triangolari
# quindi
invP = np.linalg.inv(P)
y = scipy.linalg.solve_triangular(..., lower=True, unit_diagonal=True)
my_x = scipy.linalg.solve_triangular(..., lower=False)

# if P == np.eye(n): 
# Ax = b   <--->  PLUx = b  <--->  PLy=b & Ux=y
# y = scipy.linalg.solve_triangular(np.matmul(P,L) , b, lower=True, unit_diagonal=True)
# my_x = scipy.linalg.solve_triangular(U, y, lower=False)

print('\nSoluzione calcolata: ', my_x)
print('norm =', scipy.linalg.norm(x-my_x, 'fro'))

### 2.2) Decomposizione di Cholesky
Si ripeta l’esercizio precedente sulla matrice di Hilbert, che si può generare con la funzione A = `scipy.linalg.hilbert(n)` per $n = 5, . . . , 10$. In particolare:
• Calcolare il numero di condizionamento di $A$ e rappresentarlo in un grafico al variare di $n$.
• Considerare il vettore colonna $x = (1, . . . , 1)^T$ , calcola il corrispondente termine noto $b$ per il sistema lineare $Ax = b$ e la relativa soluzione $\tilde{x}$ usando la fattorizzazione di Cholesky come nel caso precedente.
• Si rappresenti l’errore relativo al variare delle dimensioni della matrice.
**NB** La decomposizione di Cholesky viene calcolata con la funzione `scipy.linalg.cholesky`.

In [0]:
import matplotlib.pyplot as plt
# help (scipy.linalg.cholesky)
# help (scipy.linalg.hilbert)

# crazione dati e problema test
n = 5
A = ...
x = np.ones((n,1))
b = ...

condA = ...

print('x: \n', x , '\n')
print('x.shape: ', x.shape, '\n' )
print('b: \n', b , '\n')
print('b.shape: ', b.shape, '\n' )
print('A: \n', A, '\n')
print('A.shape: ', A.shape, '\n' )
print('K(A)=', condA, '\n')

L = ...
print('L:', L, '\n')

print('L.T*L =', scipy.linalg.norm(A-np.matmul(np.transpose(L),L)))
print('err = ', scipy.linalg.norm(A-np.matmul(np.transpose(L),L), 'fro'))

y = ...
my_x = ...
print('my_x = \n ', my_x)

print('norm =', np.linalg.norm(x-my_x, 'fro'))


K_A = np.zeros((6,1))
Err = np.zeros((6,1))

for n in np.arange(5,11):
    # crazione dati e problema test
    A = ...
    x = ...
    b = ...
    
    # numero di condizione 
    K_A[n-5] = ...
    
    # fattorizzazione 
    L = ...
    y = ...
    my_x = ...
    
    # errore relativo
    Err[n-5] = np.linalg.norm(x-my_x, 'fro')/np.linalg.norm(x, 'fro')
  
xplot = np.arange(5,11)

# grafico del numero di condizione vs dim
plt.semilogy(...)
plt.title('CONDIZIONAMENTO DI A ')
plt.xlabel('dimensione matrice: n')
plt.ylabel('K(A)')
plt.show()


# grafico errore in norma 2 in funzione della dimensione del sistema
plt.plot(...)
plt.title('Errore relativo')
plt.xlabel('dimensione matrice: n')
plt.ylabel('Err= ||my_x-x||/||x||')
plt.show()